name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Zip extensions
        run: |
          pnpm zip

      - name: add to release
        run: |
          # 使用触发工作流的 Release 的标签名称
          TAG_NAME=${{ github.event.release.tag_name }}
          
          # 上传 dist 目录下的所有 zip 文件到 Release
          for zip_file in dist/*.zip; do
            echo "上传文件: $zip_file 到 Release: $TAG_NAME"
            gh release upload "$TAG_NAME" "$zip_file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        